package com.netsdl.android.db;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public abstract class DatabaseHandler extends SQLiteOpenHelper {

	private static final int DATABASE_VERSION = 1;
	private static final String DATABASE_NAME = "netsdlWmsDB";

	public DatabaseHandler(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION);
		Log.d("DatabaseHandler", "new Database:" + DATABASE_NAME + " version:"
				+ DATABASE_VERSION);
	}

	@Override
	public void onOpen(SQLiteDatabase db) {
		db.execSQL(getCreateTableSql());
		super.onOpen(db);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		Log.d(getTableName(), "onCreate");
		db.execSQL(getCreateTableSql());
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		Log.d(getTableName(), "onUpgrade");
		db.execSQL("DROP TABLE IF EXISTS " + getTableName());
		onCreate(db);
	}

	public void clear() {
		SQLiteDatabase db = null;
		try {
			db = this.getWritableDatabase();
			db.execSQL("DROP TABLE IF EXISTS " + getTableName());
			db.execSQL(getCreateTableSql());
		} finally {
			if (db != null)
				db.close();
		}
	}

	/**
	 * 
	 * @param whereArgs
	 * @param whereClause
	 * @return
	 */
	public int count(String whereClause,String[] whereArgs)
	{
		SQLiteDatabase db = null;
		try {
			db = this.getReadableDatabase();
			Cursor mCount= null;
			if(whereClause==null)
			{
				mCount = db.rawQuery("select count(*) from "+getTableName(),null);
			}
			else
			{
				mCount = db.rawQuery("select count(*) from "+getTableName()+" "+whereClause, whereArgs);
			}
			mCount.moveToFirst();
			int count= mCount.getInt(0);
			mCount.close();
			return count;
		} finally {
			if (db != null)
				db.close();
		}
	}

    /**
     * 
     * @param whereClause
     * @param whereArgs
     * @return
     */
	public void delete(String whereClause,String[] whereArgs)
    {
		SQLiteDatabase db = null;
		try {
			db = this.getWritableDatabase();
			//无查询条件建议使用1=1
			if(whereClause==null)
			{
				return;
			}
			else if(whereArgs==null)
			{
				db.execSQL("delete from "+getTableName()+" where "+whereClause);
			}
			else
			{
				db.execSQL("delete from "+getTableName()+" where "+whereClause, whereArgs);
			}
			
		} finally {
			if (db != null)
				db.close();
		}
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
	public long insert(Map data,String nullColumnHack)
    {
		SQLiteDatabase db = null;
		try {
			db = this.getWritableDatabase();
			String[] columns = getColumns();
			ContentValues values = new ContentValues();

			for (int i = 0; i < columns.length; i++) {
				Object obj = data.get(columns[i]);
				if (obj == null) {
					values.put(columns[i], "");
				} else if (obj instanceof String) {
					values.put(columns[i], obj.toString());
				} else if (obj instanceof Integer) {
					values.put(columns[i], (Integer) obj);
				} else if (obj instanceof BigDecimal) {
					values.put(columns[i], ((BigDecimal) obj).toString());
				}
			}
			long l = db.insert(getTableName(), nullColumnHack, values);
			return l;
		} finally {
			if (db != null)
				db.close();
		}
	}
	
	public List<Map> findAll()
	{
		return find (false,getColumns(),null,null,null,null,null,null);
	}
	
	public List<Map> find(String[] columns,String selection,String[] selectionArgs)
	{
		return find (false,columns,selection,selectionArgs,null,null,null,null);
	}

    /**
     *
     * @mbggenerated
     */
	public List<Map> find(boolean distinct,String[] columns,String selection,String[] selectionArgs,String groupBy,String having,String orderBy,String limit){
		SQLiteDatabase db = null;
		try {
			db = this.getReadableDatabase();
			if(columns==null)
			{
				columns = getColumns();
			}
			Class<?>[] types = getTypes();
			Cursor cursor = db.query(distinct, getTableName(), columns, selection, selectionArgs, groupBy, having, orderBy, limit);
			if(cursor.isAfterLast())
				return null;
			if(cursor.isBeforeFirst())
				cursor.moveToFirst();
			List l = new ArrayList();
			do {
				Map m = new HashMap();
				for (int j = 0; j < columns.length; j++) {
					int p = getPosition(columns[j]);
					if(p==-1)
					{
						m.put(columns[j], cursor.getString(j));
					}
					else
						m.put(columns[j], convertStringToOjbect(types[p],cursor.getString(j)));
				}
				l.add(m);
			} while (cursor.moveToNext());
			return l;
		} finally {
			if (db != null)
				db.close();
		}
	}
	
	//得到行的位置
	private int getPosition(String column)
	{
		String[] cls = getColumns();
		for(int i=0;i<cls.length;i++)
		{
			if(column.equals(cls[i]))
				return i;
		}
		return -1;
	}
    
    /**
     * 
     * @param record
     * @param example
     * @return
     */
	public long update(Map data,String whereClause,String[] whereArgs)
    {
		SQLiteDatabase db = null;
		try {
			db = this.getWritableDatabase();
			String[] columns = getColumns();
			ContentValues values = new ContentValues();

			for (int i = 0; i < columns.length; i++) {
				Object obj = data.get(columns[i]);
				if (obj == null) {
					continue;
				} else if (obj instanceof String) {
					values.put(columns[i], obj.toString());
				} else if (obj instanceof Integer) {
					values.put(columns[i], (Integer) obj);
				} else if (obj instanceof BigDecimal) {
					values.put(columns[i], ((BigDecimal) obj).toString());
				}
			}
			long l = db.update(getTableName(), values, whereClause, whereArgs);
			return l;
		} finally {
			if (db != null)
				db.close();
		}
	}

  
    
    private Object convertStringToOjbect(Class<?> type, String str) {
		if (str == null)
			return null;
		str = str.trim();
		if (type.equals(String.class)) {
			return str;
		} else if (type.equals(Integer.class)) {
			if ("NULL".equals(str)) {
				return null;
			} else {
				try {
					byte[] ss = str.getBytes();
					byte[] ss2 = new byte[ss.length];
					int c = 0;
					for(int i=0;i<ss.length;i++)
					{
						if(ss[i]<0)
							continue;
						ss2[c] = ss[i];
						c++;
					}
					byte[] ss3 = new byte[c];
					System.arraycopy(ss2, 0, ss3, 0, c);
					String str2 = new String(ss3);
					Integer iTemp = Integer.valueOf(str2);
					return iTemp;
				} catch (NumberFormatException nfe) {
					return null;
				}
			}
		} else if (type.equals(BigDecimal.class)) {
			return new BigDecimal(str);
		}
		return str;
	}

	public abstract String getTableName();

	public abstract String[] getColumns();

	public abstract String[] getKeys();

	public abstract Class<?>[] getTypes();

	public abstract Class<?>[] getKeyTypes();

	public abstract String getCreateTableSql();

}
